sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.cache/yarn

before_install:
  - docker pull majiky/node8-chrome
  - docker run -td -v $TRAVIS_BUILD_DIR:/ci -v $HOME/.cache/yarn:/home/root/.cache/yarn -w /ci --name ci majiky/node8-chrome
  - docker ps

before_script:
  - docker exec ci yarn

script:
  - docker exec ci ls -l
